In [1]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

import warnings 
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('data/airbnb-data.csv')
df.head(3)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN

In [3]:
# change col names to lowercase n replace " " with underscore
df.columns = [col.lower().replace(" ","_") for col in df.columns]
df.columns

Index(['id', 'name', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'lat', 'long', 'country',
       'country_code', 'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'review_rate_number', 'calculated_host_listings_count',
       'availability_365', 'house_rules', 'license'],
      dtype='object')

In [4]:
# summary of dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   name                            102349 non-null  object
 2   host_id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host_name                       102193 non-null  object
 5   neighbourhood_group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country_code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room_type                       102599 non-null  object
 14  construction_year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service_fee                     102326 non-null  object
 17  minimum_nights                  102190 non-null  float64
 18  number_of_reviews               102416 non-null  float64
 19  last_review                     86706 non-null   object
 20  reviews_per_month               86720 non-null   float64
 21  review_rate_number              102273 non-null  float64
 22  calculated_host_listings_count  102280 non-null  float64
 23  availability_365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

# **Data Cleaning**

Important columns:
- price
- room_type
- lat
- long
- neighbourhood_group
- neighbourhood
- construction_year
- instant_bookable
- minimum_nights
- availability_365

In [5]:
df.duplicated().sum()

np.int64(541)

In [6]:
df.isnull().sum()

id                                     0
name                                 250
host_id                                0
host_identity_verified               289
host_name                            406
neighbourhood_group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
country_code                         131
instant_bookable                     105
cancellation_policy                   76
room_type                              0
construction_year                    214
price                                247
service_fee                          273
minimum_nights                       409
number_of_reviews                    183
last_review                        15893
reviews_per_month                  15879
review_rate_number                   326
calculated_host_listings_count       319
availability_365                     448
house_rules                        52131
license                           102597
dtype: int64

In [7]:
# dropping duplicate values first
df.drop_duplicates(inplace=True)

In [8]:
df.columns

Index(['id', 'name', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'lat', 'long', 'country',
       'country_code', 'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'review_rate_number', 'calculated_host_listings_count',
       'availability_365', 'house_rules', 'license'],
      dtype='object')

#### **1. price column**

In [9]:
# change price from str to int
df.price = df.price.str.replace('$','')
df.price = df.price.str.replace(',','')

# drop rows with null/NaN values
df.dropna(subset=['price'], inplace=True)
df.price = df.price.astype(int)

print(df.price.dtype)

int64

#### **2. room_type column**
There are 4 different types:
- Entire home/apt
- Private room
- Shared room
- Hotel room

In [10]:
print(df['room_type'].value_counts())

# there are 0 null values
print(df['room_type'].isnull().sum())

room_type
Entire home/apt    53296
Private room       46200
Shared room         2200
Hotel room           115
Name: count, dtype: int64
0

#### **3. lat column (latitude)**

In [11]:
print(df['lat'].value_counts())

# there were 8 null values
print(df['lat'].isnull().sum())

df.dropna(subset=['lat'], inplace=True)
print(df['lat'].isnull().sum())

lat
40.76411    36
40.71813    32
40.76125    27
40.73756    26
40.71353    25
            ..
40.66861     1
40.85125     1
40.77165     1
40.79066     1
40.78643     1
Name: count, Length: 21979, dtype: int64
8
0

#### **4. long column (longitude)**

In [12]:
print(df['long'].isnull().sum())
df.dropna(subset=['long'], inplace=True)

0

In [13]:
df.isnull().sum()

id                                     0
name                                 247
host_id                                0
host_identity_verified               285
host_name                            399
neighbourhood_group                   28
neighbourhood                         15
lat                                    0
long                                   0
country                              527
country_code                         126
instant_bookable                     100
cancellation_policy                   71
room_type                              0
construction_year                    209
price                                  0
service_fee                          239
minimum_nights                       400
number_of_reviews                    183
last_review                        15805
reviews_per_month                  15790
review_rate_number                   319
calculated_host_listings_count       319
availability_365                     448
house_rules                        51705
license                           101801
dtype: int64

#### **5. neighbourhood_group column**
-> Manhattan, Brooklyn, Queens, Bronx, Staten Island

In [14]:
print(df['neighbourhood_group'].value_counts())

neighbourhood_group
Manhattan        43443
Brooklyn         41534
Queens           13163
Bronx             2687
Staten Island      946
brookln              1
manhatan             1
Name: count, dtype: int64

In [15]:
# rename the mistyped/typo neighbourhood_group values
df['neighbourhood_group'] = df['neighbourhood_group'].replace({
    'brookln': 'Brooklyn',
    'manhatan': 'Manhattan'
})


print(df['neighbourhood_group'].value_counts())

neighbourhood_group
Manhattan        43444
Brooklyn         41535
Queens           13163
Bronx             2687
Staten Island      946
Name: count, dtype: int64

In [16]:
# drop the rows with null neighbourhood_group
df.dropna(subset=['neighbourhood_group'], inplace=True)
print(df['neighbourhood_group'].isnull().sum())

0

#### **6. neighbourhood column**

In [17]:
print(df['neighbourhood'].value_counts())

# there were 15 null values
# drop rows with null neighbourhood values
df.dropna(subset=['neighbourhood'], inplace=True)
print(df['neighbourhood'].isnull().sum())

neighbourhood
Bedford-Stuyvesant        7881
Williamsburg              7708
Harlem                    5428
Bushwick                  4937
Hell's Kitchen            3945
                          ...
Rossville                    3
Gerritsen Beach              3
Fort Wadsworth               2
Glen Oaks                    2
Chelsea, Staten Island       1
Name: count, Length: 224, dtype: int64
0

#### **7. construction_year column**

In [18]:
print('Range of construction_year = {} - {}\n' .format(df['construction_year'].min(), df['construction_year'].max()))
print(df['construction_year'].value_counts())

# there were 204 null rows
# fill null values with median, which is 2012
df['construction_year'].fillna(df['construction_year'].median(), inplace=True)
print(df['construction_year'].isnull().sum())

Range of construction_year = 2003.0 - 2022.0

construction_year
2014.0    5203
2008.0    5183
2006.0    5174
2019.0    5156
2009.0    5131
2020.0    5120
2010.0    5118
2022.0    5095
2005.0    5088
2012.0    5086
2003.0    5084
2007.0    5073
2015.0    5055
2017.0    5025
2011.0    5016
2018.0    5013
2021.0    4995
2004.0    4993
2013.0    4977
2016.0    4971
Name: count, dtype: int64
0

In [19]:
df.isnull().sum()

id                                     0
name                                 245
host_id                                0
host_identity_verified               277
host_name                            398
neighbourhood_group                    0
neighbourhood                          0
lat                                    0
long                                   0
country                              525
country_code                         124
instant_bookable                      98
cancellation_policy                   69
room_type                              0
construction_year                      0
price                                  0
service_fee                          239
minimum_nights                       398
number_of_reviews                    183
last_review                        15801
reviews_per_month                  15788
review_rate_number                   317
calculated_host_listings_count       319
availability_365                     436
house_rules                        51692
license                           101758
dtype: int64

#### **8. instant_bookable column** 
Either True or False

In [20]:
print(df['instant_bookable'].value_counts())

# there were 105 null values
# fill the null values with False
df['instant_bookable'].fillna(False, inplace=True)
print(df['instant_bookable'].isnull().sum())

instant_bookable
False    51040
True     50622
Name: count, dtype: int64
0

#### **9. minimum_nights column**

In [21]:
# clip the min and max values to be from 1-365 only
df['minimum_nights'] = df['minimum_nights'].clip(1, 365)
df['minimum_nights'] = df['minimum_nights'].fillna(df['minimum_nights'].median())
df['minimum_nights'] = df['minimum_nights'].astype('Int64')

print('Range of minimum_nights = {} - {}\n' .format(df['minimum_nights'].min(), df['minimum_nights'].max()))

print(df['minimum_nights'].value_counts())

Range of minimum_nights = 1 - 365

minimum_nights
1      25245
2      23433
3      16394
30     11507
4       6587
       ...
364        1
333        1
119        1
125        1
34         1
Name: count, Length: 124, dtype: Int64

In [22]:
# there were 398 null values
# fill null values with median
print(df['minimum_nights'].median())

3.0

#### **10. availability_365 column**

In [23]:
print('Range of availability_365 = {} - {}\n' .format(df['availability_365'].min(), df['availability_365'].max()))
# print(df['availability_365'].describe())
# print(df['availability_365'].value_counts())`

# fix the negative values to be 0 and values > 365 to be 365
df['availability_365'].clip(0, 365, inplace=True)

# fill the null values with median
df['availability_365'].fillna(df['availability_365'].median(), inplace=True)
print(df['availability_365'].value_counts())
print(df['availability_365'].isnull().sum())

Range of availability_365 = -10.0 - 3677.0

availability_365
0.0      23814
365.0     5221
364.0     1158
89.0       744
1.0        731
         ...
210.0       90
181.0       87
202.0       85
195.0       81
187.0       78
Name: count, Length: 366, dtype: int64
0

#### **11. cancellation_policy column**

In [24]:
# dealing with cancellation policy 
print(df['cancellation_policy'].value_counts())
df.cancellation_policy.fillna('moderate',inplace=True)

cancellation_policy
moderate    34072
strict      33826
flexible    33793
Name: count, dtype: int64

#### **12. calculated_host_listings_count column**

In [25]:
print(df['calculated_host_listings_count'].isna().sum())
# dropping rows with null as its only 0.3% of total rows
df.dropna(subset=['calculated_host_listings_count'], inplace=True)

319

#### **13. number_of_reviews column**

In [26]:
print(df['number_of_reviews'].isna().sum())
# dropping rows with null as its only 0.1% of total rows
df.dropna(subset=['number_of_reviews'], inplace=True)

183

#### **14. review_rate_number column**

In [27]:
print(df['review_rate_number'].isna().sum())
# dropping rows with null as its only 0.2% of total rows
df.dropna(subset=['review_rate_number'], inplace=True)

248

In [28]:
# country and country_code columns will be dropped as they contain only 1 value
print(df.country.value_counts())
print(df.country_code.value_counts())

country
United States    100485
Name: count, dtype: int64
country_code
US    100900
Name: count, dtype: int64

### Columns to drop entirely:
- id (not needed)
- name (not needed)
- host_id (not needed)
- host_identity_verified (not needed)
- host_name (not needed)
- country (contains only 1 value)
- country_code (contains only 1 value)
- service_fee (serve same purpose as price)
- house_rules (too much null & doesn't contribute much to current objective)
- license (too much null & doesn't contribute much to current objective)

In [29]:
colsToDrop = ['id', 'name', 'host_id', 'host_identity_verified', 'host_name','country','country_code',
              'service_fee', 'house_rules', 'license']


df = df.drop(columns=colsToDrop)
df.head(3)

,neighbourhood_group,neighbourhood,lat,long,instant_bookable,cancellation_policy,room_type,construction_year,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365
0,Brooklyn,Kensington,40.64749,-73.97237,False,strict,Private room,2020.0,966,10,9.0,10/19/2021,0.21,4.0,6.0,286.0
1,Manhattan,Midtown,40.75362,-73.98377,False,moderate,Entire home/apt,2007.0,142,30,45.0,5/21/2022,0.38,4.0,2.0,228.0
2,Manhattan,Harlem,40.80902,-73.94190,True,flexible,Private room,2005.0,620,3,0.0,NaN,NaN,5.0,1.0,352.0

In [30]:
df.isnull().sum()

neighbourhood_group                   0
neighbourhood                         0
lat                                   0
long                                  0
instant_bookable                      0
cancellation_policy                   0
room_type                             0
construction_year                     0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       15592
reviews_per_month                 15579
review_rate_number                    0
calculated_host_listings_count        0
availability_365                      0
dtype: int64

for last_review and reviews_per_month, null usually mean new or inactive listings so we will leave it for now.

## EDA

In [31]:
df.columns

Index(['neighbourhood_group', 'neighbourhood', 'lat', 'long',
       'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'price', 'minimum_nights', 'number_of_reviews',
       'last_review', 'reviews_per_month', 'review_rate_number',
       'calculated_host_listings_count', 'availability_365'],
      dtype='object')

In [32]:
df.head()

,neighbourhood_group,neighbourhood,lat,long,instant_bookable,cancellation_policy,room_type,construction_year,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365
0,Brooklyn,Kensington,40.64749,-73.97237,False,strict,Private room,2020.0,966,10,9.0,10/19/2021,0.21,4.0,6.0,286.0
1,Manhattan,Midtown,40.75362,-73.98377,False,moderate,Entire home/apt,2007.0,142,30,45.0,5/21/2022,0.38,4.0,2.0,228.0
2,Manhattan,Harlem,40.80902,-73.94190,True,flexible,Private room,2005.0,620,3,0.0,NaN,NaN,5.0,1.0,352.0
3,Brooklyn,Clinton Hill,40.68514,-73.95976,True,moderate,Entire home/apt,2005.0,368,30,270.0,7/5/2019,4.64,4.0,1.0,322.0
4,Manhattan,East Harlem,40.79851,-73.94399,False,moderate,Entire home/apt,2009.0,204,10,9.0,11/19/2018,0.10,3.0,1.0,289.0

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 101010 entries, 0 to 102057
Data columns (total 16 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   neighbourhood_group             101010 non-null  object
 1   neighbourhood                   101010 non-null  object
 2   lat                             101010 non-null  float64
 3   long                            101010 non-null  float64
 4   instant_bookable                101010 non-null  bool
 5   cancellation_policy             101010 non-null  object
 6   room_type                       101010 non-null  object
 7   construction_year               101010 non-null  float64
 8   price                           101010 non-null  int64
 9   minimum_nights                  101010 non-null  Int64
 10  number_of_reviews               101010 non-null  float64
 11  last_review                     85418 non-null   object
 12  reviews_per_month               85431 non-null   float64
 13  review_rate_number              101010 non-null  float64
 14  calculated_host_listings_count  101010 non-null  float64
 15  availability_365                101010 non-null  float64
dtypes: Int64(1), bool(1), float64(8), int64(1), object(5)
memory usage: 12.5+ MB

In [34]:
df.describe()

,lat,long,construction_year,price,minimum_nights,number_of_reviews,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365
count,101010.000000,101010.000000,101010.000000,101010.000000,101010.0,101010.000000,85431.000000,101010.000000,101010.000000,101010.000000
mean,40.728048,-73.949667,2012.486298,625.495406,7.945768,27.428868,1.376107,3.279616,7.940164,139.903713
std,0.055849,0.049526,5.758279,331.691279,18.20705,49.437324,1.748988,1.284584,32.300544,133.194751
min,40.499790,-74.249840,2003.000000,50.000000,1.0,0.000000,0.010000,1.000000,1.000000,0.000000
25%,40.688693,-73.982590,2008.000000,340.000000,2.0,1.000000,0.220000,2.000000,1.000000,3.000000
50%,40.722250,-73.954450,2012.000000,625.000000,3.0,7.000000,0.740000,3.000000,1.000000,96.000000
75%,40.762740,-73.932350,2017.000000,913.000000,5.0,30.000000,2.010000,4.000000,2.000000,268.000000
max,40.916970,-73.705220,2022.000000,1200.000000,365.0,1024.000000,90.000000,5.000000,332.000000,365.000000

In [35]:
df.isna()

,neighbourhood_group,neighbourhood,lat,long,instant_bookable,cancellation_policy,room_type,construction_year,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
102054,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
102055,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
102056,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
102057,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [36]:
df['neighbourhood_group'].unique()

array(['Brooklyn', 'Manhattan', 'Queens', 'Staten Island', 'Bronx'],
      dtype=object)

In [37]:
df['neighbourhood'].unique()

array(['Kensington', 'Midtown', 'Harlem', 'Clinton Hill', 'East Harlem',
       'Murray Hill', 'Bedford-Stuyvesant', "Hell's Kitchen",
       'Upper West Side', 'Chinatown', 'South Slope', 'West Village',
       'Williamsburg', 'Fort Greene', 'Chelsea', 'Crown Heights',
       'Park Slope', 'Windsor Terrace', 'Bushwick', 'Flatbush',
       'Lower East Side', 'East Village', 'Greenpoint', 'Kips Bay',
       'SoHo', 'Upper East Side', 'Prospect Heights', 'Brooklyn Heights',
       'Gowanus', 'Flatlands', 'Cobble Hill', 'Flushing', 'Boerum Hill',
       'Sunnyside', 'DUMBO', 'Carroll Gardens', 'St. George',
       'Highbridge', 'Financial District', 'Ridgewood',
       'Morningside Heights', 'Jamaica', 'Middle Village',
       'Ditmars Steinway', 'Flatiron District', 'Roosevelt Island',
       'Greenwich Village', 'Little Italy', 'Tompkinsville', 'Astoria',
       'Clason Point', 'Inwood', 'Washington Heights', 'Kingsbridge',
       'Two Bridges', 'Rockaway Beach', 'East Flatbush', 'Nolita',
       'Woodlawn', 'Gramercy', 'Allerton', 'East New York',
       'Prospect-Lefferts Gardens', 'Theater District',
       'Concourse Village', 'Sheepshead Bay', 'Emerson Hill',
       'Long Island City', 'Fort Hamilton', 'Bensonhurst', 'NoHo',
       'Tribeca', 'Shore Acres', 'Sunset Park', 'Concourse', 'Elmhurst',
       'Brighton Beach', 'Jackson Heights', 'Cypress Hills', 'St. Albans',
       'Arrochar', 'Rego Park', 'Wakefield', 'Woodside', 'Clifton',
       'Bay Ridge', 'Graniteville', 'Spuyten Duyvil', 'Stapleton',
       'Briarwood', 'Ozone Park', 'Columbia St', 'Vinegar Hill',
       'Mott Haven', 'Longwood', 'Canarsie', 'Battery Park City',
       'Civic Center', 'East Elmhurst', 'New Springville',
       'Morris Heights', 'Arverne', 'Gravesend', 'Cambria Heights',
       'Tottenville', 'Mariners Harbor', 'Concord', 'Borough Park',
       'Bayside', 'Downtown Brooklyn', 'Port Morris', 'Fieldston',
       'Kew Gardens', 'Midwood', 'College Point', 'Mount Eden',
       'City Island', 'Glendale', 'Port Richmond', 'Red Hook',
       'Richmond Hill', 'Queens Village', 'Bellerose', 'Maspeth',
       'Williamsbridge', 'Soundview', 'Woodhaven', 'Forest Hills',
       'Woodrow', 'Co-op City', 'Stuyvesant Town', 'Parkchester',
       'North Riverdale', 'Dyker Heights', 'Bronxdale', 'Sea Gate',
       'Riverdale', 'Kew Gardens Hills', 'Bay Terrace', 'Norwood',
       'Claremont Village', 'Whitestone', 'Fordham', 'University Heights',
       'Bayswater', 'Navy Yard', 'Brownsville', 'Eltingville',
       'Fresh Meadows', 'Mount Hope', 'Lighthouse Hill',
       'Springfield Gardens', 'Eastchester', 'Howard Beach',
       'Belle Harbor', 'Van Nest', 'Morris Park', 'West Brighton',
       'Far Rockaway', 'South Ozone Park', 'Tremont', 'Corona',
       'Great Kills', 'Jamaica Estates', 'Manhattan Beach', 'Marble Hill',
       'Dongan Hills', 'Castleton Corners', 'East Morrisania',
       'Hunts Point', 'Neponsit', 'Pelham Bay', 'Randall Manor',
       'Throgs Neck', 'Todt Hill', 'West Farms', 'Silver Lake',
       'Morrisania', 'Laurelton', 'Grymes Hill', 'Holliswood',
       'Pelham Gardens', 'Belmont', 'Rosedale', 'Edgemere',
       'New Brighton', 'Midland Beach', 'Baychester', 'Melrose',
       'Bergen Beach', 'Richmondtown', 'Howland Hook', 'Schuylerville',
       'Coney Island', 'New Dorp Beach', "Prince's Bay", 'South Beach',
       'Bath Beach', 'Jamaica Hills', 'Oakwood', 'Castle Hill', 'Hollis',
       'Douglaston', 'Huguenot', 'Olinville', 'Edenwald', 'Grant City',
       'Westerleigh', 'Bay Terrace, Staten Island', 'Westchester Square',
       'Little Neck', 'Fort Wadsworth', 'Rosebank', 'Unionport',
       'Mill Basin', 'Arden Heights', "Bull's Head", 'New Dorp',
       'Rossville', 'Breezy Point', 'Willowbrook', 'Glen Oaks',
       'Gerritsen Beach', 'Chelsea, Staten Island'], dtype=object)

sns.heatmap(df.select_dtypes(include=['number']).corr(), annot=True)

In [38]:
# Make sure these columns exist and are in correct type first
df['price'] = pd.to_numeric(df['price'], errors='coerce')
df['availability_365'] = pd.to_numeric(df['availability_365'], errors='coerce')
df['last_review'] = pd.to_datetime(df['last_review'], errors='coerce')

### Derived columns

#### **1. Occupancy Rate**

In [39]:
df['occupancy_rate'] = (365 - df['availability_365']) / 365

#### **2. Estimated occupied nights per year**

In [40]:
df['estimated_occupied_nights'] = 365 - df['availability_365']

#### **3. Estimated yearly revenue**

In [41]:
df['estimated_revenue'] = df['price'] * df['estimated_occupied_nights']

In [42]:
print(df[['occupancy_rate', 'estimated_occupied_nights', 
          'estimated_revenue']].describe())

       occupancy_rate  estimated_occupied_nights  estimated_revenue
count   101010.000000              101010.000000      101010.000000
mean         0.616702                 225.096287      140933.463281
std          0.364917                 133.194751      120386.667702
min          0.000000                   0.000000           0.000000
25%          0.265753                  97.000000       34650.000000
50%          0.736986                 269.000000      111159.000000
75%          0.991781                 362.000000      227103.000000
max          1.000000                 365.000000      438000.000000

In [43]:
df = df[df["price"] > 0]

df["log_price"] = np.log(df["price"])
df["log_price"]

0         6.873164
1         4.955827
2         6.429719
3         5.908083
4         5.318120
            ...
102053    6.545350
102054    6.812345
102055    5.958425
102056    6.742881
102057    7.028201
Name: log_price, Length: 101010, dtype: float64

In [44]:
df.head(1)

,neighbourhood_group,neighbourhood,lat,long,instant_bookable,cancellation_policy,room_type,construction_year,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,occupancy_rate,estimated_occupied_nights,estimated_revenue,log_price
0,Brooklyn,Kensington,40.64749,-73.97237,False,strict,Private room,2020.0,966,10,9.0,2021-10-19,0.21,4.0,6.0,286.0,0.216438,79.0,76314.0,6.873164

In [45]:
df.to_csv("data/airbnb_price_cleaned.csv", index=False)